name: Black Code Formatting

on: [push]

jobs:
  black:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Black
        run: |
          python -m pip install --upgrade pip
          pip install black
      - name: Check code format with Black
        run: |
          black --check .
